### ISSUE TITLE
QA Proposal Details

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-gov-proposal-app#5]
### Proposal Details
![od-gov-proposal](https://github.com/open-dollar/od-gov-proposal-app/assets/35622595/9dc23360-9137-461a-a5d5-d2c196456f8a)
- [ ] Overall- reduce the amount of white space, use consistent font-sizes and heading text. 
- [ ] left-align text
- [ ] Remove large blue bar under section headings headings
- [ ] Remove box border for "Decoded Arguments" and move to bottom of list

**Comment by alekseevaiana** [comment]
I actually don't see any data on the page.

**Comment by pi0neerpat** [comment]
Completed in #13
